id = "mcp-server-relytone"
name = "RelytONE MCP Server"
description = "Model Context Protocol Server for RelytONE workspaces"
version = "0.1.0"
schema_version = 1
authors = ["Yuwei XIAO <ywxiaozero@gmail.com>"]
repository = "https://github.com/YuweiXiao/zed-mcp-server-relytone.git"

[context_servers.mcp-server-relytone]
name = "RelytONE MCP Server"
